version: '3.1'

services:
  migration:
    build: .
    command: flask db upgrade
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DB}
      - SECRET_KEY=${SECRET_KEY}

  web:
    build: .
    command: gunicorn -b 0.0.0.0:80 your_application:app
    ports:
      - "5000:80"
    depends_on:
      - migration
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DB}
      - SECRET_KEY=${SECRET_KEY}

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # It's advisable to change 'rootpassword' to a more secure password
      - MYSQL_DATABASE=${MYSQL_DB}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
